# Generated by Django 2.2.28 on 2024-03-15 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('face', models.ImageField(upload_to='')),
                ('stop', models.IntegerField()),
                ('soft', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=40)),
                ('directory', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('currency', models.CharField(choices=[('GBP', 'GBP'), ('EUR', 'EUR'), ('USD', 'USD'), ('MXN', 'MXN'), ('AUD', 'AUD'), ('JPY', 'JPY')], default='GBP', max_length=24)),
                ('pfp', models.ImageField(blank=True, default='media/images/pfp/default_pfp.png', upload_to='media/images/pfp')),
                ('banner', models.ImageField(blank=True, default='media/images/banner/default_banner.png', upload_to='media/images/banner')),
                ('blackjack_state', models.TextField(default='{}')),
                ('slug', models.SlugField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('depositAmount', models.FloatField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='Corruption_Cove.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(default='slug')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Corruption_Cove.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('name', models.CharField(max_length=40)),
                ('cardNo', models.CharField(max_length=16)),
                ('expiry', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('slug', models.SlugField(default='slug', unique=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banking', to='Corruption_Cove.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_r', to='Corruption_Cove.UserProfile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_r', to='Corruption_Cove.UserProfile')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_f', to='Corruption_Cove.UserProfile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_f', to='Corruption_Cove.UserProfile')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
