# Generated by Django 5.0.2 on 2024-02-25 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corruption_Cove', '0002_userprofile_currency_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Corruption_Cove.userprofile')),
            ],
        ),
    ]
