# Generated by Django 5.0.2 on 2024-02-27 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corruption_Cove', '0004_friendship_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('name', models.CharField(max_length=40)),
                ('cardNo', models.CharField(max_length=16)),
                ('expiry', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banking', to='Corruption_Cove.userprofile', unique=True)),
            ],
        ),
    ]
