# Generated by Django 5.0.2 on 2024-02-27 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corruption_Cove', '0005_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banking', to='Corruption_Cove.userprofile'),
        ),
    ]
