# Generated by Django 5.0.2 on 2024-03-01 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corruption_Cove', '0006_alter_bank_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
        migrations.AddField(
            model_name='request',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banking', to='Corruption_Cove.userprofile', unique=True),
        ),
    ]
