# Generated by Django 5.0.2 on 2024-03-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corruption_Cove', '0007_bank_slug_request_slug_alter_bank_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='slug',
        ),
        migrations.AddField(
            model_name='bet',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
    ]
