# Generated by Django 5.0.2 on 2024-03-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corruption_Cove', '0008_remove_request_slug_bet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='banner',
            field=models.ImageField(blank=True, default='media/images/pfp/default_banner.png', upload_to='media/images/banner'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pfp',
            field=models.ImageField(blank=True, default='media/images/pfp/default_pfp.png', upload_to='media/images/pfp'),
        ),
    ]
