# Generated by Django 5.0.2 on 2024-03-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corruption_Cove', '0009_alter_userprofile_banner_alter_userprofile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='banner',
            field=models.ImageField(blank=True, default='media/images/banner/default_banner.png', upload_to='media/images/banner'),
        ),
    ]
