# Generated by Django 5.0.2 on 2024-03-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Corruption_Cove', '0010_alter_bank_id_alter_bet_id_alter_friendship_id_and_more'),
        ('Corruption_Cove', '0010_alter_userprofile_banner'),
    ]

    operations = [
    ]
