# Generated by Django 2.2.28 on 2024-03-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Corruption_Cove', '0011_merge_20240304_1517'),
        ('Corruption_Cove', '0007_auto_20240301_1512'),
    ]

    operations = [
    ]
