# Generated by Django 5.0.2 on 2024-03-07 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corruption_Cove', '0012_dealer_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 7)),
        ),
    ]
