# Generated by Django 5.0.2 on 2024-03-07 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corruption_Cove', '0013_alter_bet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
