# Generated by Django 5.0.2 on 2024-03-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corruption_Cove', '0014_alter_bet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
