# Generated by Django 4.2.10 on 2024-03-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Corruption_Cove", "0012_merge_20240304_2006"),
        ("Corruption_Cove", "0015_alter_bet_slug"),
    ]

    operations = []
