# Generated by Django 5.0.2 on 2024-03-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Corruption_Cove', '0012_merge_20240304_2006'),
        ('Corruption_Cove', '0015_alter_bet_slug'),
    ]

    operations = [
    ]
