# Generated by Django 5.0.1 on 2024-03-09 00:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Corruption_Cove",
            "0017_alter_bank_id_alter_bank_username_alter_bet_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
