# Generated by Django 4.2.10 on 2024-03-08 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "Corruption_Cove",
            "0017_alter_bank_id_alter_bank_username_alter_bet_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
