# Generated by Django 5.0.1 on 2024-03-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Corruption_Cove", "0018_alter_bet_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="blackjack_state",
            field=models.TextField(default="{}"),
        ),
    ]
