# Generated by Django 4.2.10 on 2024-03-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Corruption_Cove", "0019_userprofile_blackjack_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="expiry",
            field=models.CharField(help_text="MM/YY", max_length=5),
        ),
    ]
